# FUNDING.yml
# Uncomment the relevant lines below to enable GitHub Sponsors or other funding platforms
# github: your-github-username
# patreon: your-patreon-username
# open_collective: your-collective
# ko_fi: your-kofi-username
# custom: ['https://your-custom-funding-link.com']
