name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          npm install || true
      - name: Lint (if config present)
        run: |
          if [ -f .eslintrc.json ]; then npx eslint .; else echo "No ESLint config"; fi
      - name: Run tests (if present)
        run: |
          if [ -d tests ]; then npm test || echo "No tests"; else echo "No tests directory"; fi
